alias minikube-start='minikube start; ~/dev/core/vault/k8s/minkube-ecr-login.sh;'
alias pb='plz build'
alias pt='plz test' 
alias pw='plz watch'
alias aws-login='$(aws ecr get-login)'
alias k=kubectl
alias kcontext='kubectl config use-context'
alias vim=nvim
alias core3='cd ~/dev/core3/src'
alias dotfiles='cd ~/dev/dotfiles'
